### ISSUE TITLE
journey does not work with docker version

### ISSUE THREAD

**Issue by hkokko** [adoroszlai/docker-mermaid.cli#1]
journey type graphs throw errors with docker. The same graph works in the node npc version. Could it be possible that docker version has old mermaid in it?

**Comment by adoroszlai** [comment]
Thanks @hkokko for reporting this.  I have not updated the docker image with new versions of mermaid for quite some time.  Now mermaid-cli has an [official docker image](https://github.com/mermaid-js/mermaid-cli#use-docker), so I don't think mine is still relevant.
